name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3  # Use the latest version
        id: snake-gif
        with:
          github_user_name: kholoud0
          outputs: dist/github-contribution-grid-snake2.svg
          color_snake: blue  # Changed to `color_snake`

      # Push to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Use the latest version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has the necessary permissions
